spring.application.name=ems
server.port=8080

spring.datasource.url=postgresql://project_emp_user:yPbwKAtrsDQpAqFgl09Vbo5krKNG8m3a@dpg-d95ntn0js32c7384fjmg-a/project_emp
spring.datasource.username=project_emp_user
spring.datasource.password=yPbwKAtrsDQpAqFgl09Vbo5krKNG8m3a
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect